#! /usr/bin/env bash

# The Figlet font is DOS Rebel from https://github.com/xero/figlet-fonts/blob/master/Examples.md

#    █████████               █████                      █████                         █████
#   ███░░░░░███             ░░███                      ░░███                         ░░███
#  ░███    ░███  █████ ████ ███████    ██████   █████  ███████    ██████   ████████  ███████
#  ░███████████ ░░███ ░███ ░░░███░    ███░░███ ███░░  ░░░███░    ░░░░░███ ░░███░░███░░░███░
#  ░███░░░░░███  ░███ ░███   ░███    ░███ ░███░░█████   ░███      ███████  ░███ ░░░   ░███
#  ░███    ░███  ░███ ░███   ░███ ███░███ ░███ ░░░░███  ░███ ███ ███░░███  ░███       ░███ ███
#  █████   █████ ░░████████  ░░█████ ░░██████  ██████   ░░█████ ░░████████ █████      ░░█████
# ░░░░░   ░░░░░   ░░░░░░░░    ░░░░░   ░░░░░░  ░░░░░░     ░░░░░   ░░░░░░░░ ░░░░░        ░░░░░

isoverlord=false

if [ $(uname -n) = "overlord" ]; then
  isoverlord=true
fi
# My display setup

# Load environment variables
source "$HOME/.config/river/environment.sh"
# Load hellwal colors to apply to borders
# source "$HOME/.cache/hellwal/variables.sh"
wlr-randr --output HDMI-A-1 --mode 1356x768 --transform normal --pos 1366,768
wlr-randr --output eDP-1 --mode 1366x768 --pos 0,0 --adaptive-sync disabled

# Autostart

#   █████████            █████     █████     ███
#  ███░░░░░███          ░░███     ░░███     ░░░
# ░███    ░░░   ██████  ███████   ███████   ████  ████████    ███████  █████
# ░░█████████  ███░░███░░░███░   ░░░███░   ░░███ ░░███░░███  ███░░███ ███░░
#  ░░░░░░░░███░███████   ░███      ░███     ░███  ░███ ░███ ░███ ░███░░█████
#  ███    ░███░███░░░    ░███ ███  ░███ ███ ░███  ░███ ░███ ░███ ░███ ░░░░███
# ░░█████████ ░░██████   ░░█████   ░░█████  █████ ████ █████░░███████ ██████
#  ░░░░░░░░░   ░░░░░░     ░░░░░     ░░░░░  ░░░░░ ░░░░ ░░░░░  ░░░░░███░░░░░░
#                                                            ███ ░███
#                                                           ░░██████
#                                                            ░░░░░░

# Settings
# Set background and border color
riverctl background-color "0x${color8}"
riverctl border-width 1
riverctl border-color-focused "0x${color6}"
riverctl border-color-unfocused "0x${color1}"

riverctl set-repeat 30 300
riverctl default-attach-mode bottom
riverctl focus-follows-cursor always
riverctl hide-cursor timeout 10000 # 10 Seconds in milliseconds
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme "Bibata-Modern-Ice" 18

# Touchpad Settings
configure_input() {
  device="$1"
  shift
  for opt in "$@"; do
    riverctl input "$device" $opt
  done
}
# Get device name from riverctl list-inputs
tp="pointer-2-14-ETPS/2_Elantech_Touchpad"
configure_input "$tp" \
  "tap enabled" \
  "accel-profile flat" \
  "natural-scroll enabled" \
  "disable-while-typing enabled" \
  "disable-while-trackpointing enabled"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 -main-ratio 0.5 -main-count 1 &

#  █████   █████                      ███            █████     ████
# ░░███   ░░███                      ░░░            ░░███     ░░███
#  ░███    ░███   ██████   ████████  ████   ██████   ░███████  ░███   ██████   █████
#  ░███    ░███  ░░░░░███ ░░███░░███░░███  ░░░░░███  ░███░░███ ░███  ███░░███ ███░░
#  ░░███   ███    ███████  ░███ ░░░  ░███   ███████  ░███ ░███ ░███ ░███████ ░░█████
#   ░░░█████░    ███░░███  ░███      ░███  ███░░███  ░███ ░███ ░███ ░███░░░   ░░░░███
#     ░░███     ░░████████ █████     █████░░████████ ████████  █████░░██████  ██████
#      ░░░       ░░░░░░░░ ░░░░░     ░░░░░  ░░░░░░░░ ░░░░░░░░  ░░░░░  ░░░░░░  ░░░░░░
# Variables
terminal="footclient"
filemanager="thunar"
browser="zen"
mod="Mod4"
UserScripts="$HOME/.config/river/UserScripts"
scriptsDir="$HOME/.config/river/scripts"

# Tags
all_tags=$(((1 << 32) - 1))

sticky_tag=$((1 << 31))
special_tag=$((1 << 30))

# code_tag=$((1 << 0))
browser_tag=$((1 << 1))
file_browser_tag=$((1 << 2))
games_tag=$((1 << 3))
socials_tag=$((1 << 4))
discord_tag=$((1 << 5))
obsidian_tag=$((1 << 6))

terminal_tag=$((1 << 11))
files_tag=$((1 << 12))
dots_tag=$((1 << 13))
monitor_tag=$((1 << 14))
docs_tag=$((1 << 15))
ticktick_tag=$((1 << 16))
spotify_tag=$((1 << 17))
project_tag=$((1 << 18))

#   █████████                                █████             █████                              █████
#  ███░░░░░███                              ░░███             ░░███                              ░░███
# ░███    ░░░   ██████  ████████   ██████   ███████    ██████  ░███████   ████████   ██████    ███████
# ░░█████████  ███░░███░░███░░███ ░░░░░███ ░░░███░    ███░░███ ░███░░███ ░░███░░███ ░░░░░███  ███░░███
#  ░░░░░░░░███░███ ░░░  ░███ ░░░   ███████   ░███    ░███ ░░░  ░███ ░███  ░███ ░███  ███████ ░███ ░███
#  ███    ░███░███  ███ ░███      ███░░███   ░███ ███░███  ███ ░███ ░███  ░███ ░███ ███░░███ ░███ ░███
# ░░█████████ ░░██████  █████    ░░████████  ░░█████ ░░██████  ████ █████ ░███████ ░░████████░░████████
#  ░░░░░░░░░   ░░░░░░  ░░░░░      ░░░░░░░░    ░░░░░   ░░░░░░  ░░░░ ░░░░░  ░███░░░   ░░░░░░░░  ░░░░░░░░
#                                                                         ░███
#                                                                         █████
#                                                                        ░░░░░
# Scratchpads
scratch_tags=$((special_tag | sticky_tag | terminal_tag | files_tag | dots_tag | monitor_tag | docs_tag | ticktick_tag | spotify_tag | project_tag))

all_but_scratch_tag=$((all_tags ^ scratch_tags))
riverctl spawn-tagmask ${all_but_scratch_tag}

scratchpad="$HOME/.config/river/scratchpads.sh"

riverctl map normal $mod+Shift T spawn "$scratchpad term"
riverctl map normal $mod+Shift M spawn "$scratchpad btop"
riverctl map normal $mod+Shift E spawn "$scratchpad files"
riverctl map normal $mod+Shift N spawn "$scratchpad nvim"
riverctl map normal $mod+Shift P spawn "$scratchpad project"

# Mapping for sending to stickypad
# Show sticky windows on scratch_tags too
riverctl map normal $mod Slash toggle-view-tags $(($sticky_tag | $scratch_tags))

# mapping for sending to special_tag (Scratchpad)
riverctl map normal $mod Space set-view-tags $special_tag
riverctl map normal $mod+Shift Space toggle-focused-tags $special_tag

# Make this tags toggle with same keybind, and set rule for apps to be
# fullscreen, or else they till with active apps.
riverctl map normal $mod+Shift D toggle-focused-tags $docs_tag
riverctl map normal $mod+Shift S toggle-focused-tags $spotify_tag
riverctl map normal $mod+Shift I toggle-focused-tags $ticktick_tag

#  ███████████   ███                 █████
# ░░███░░░░░███ ░░░                 ░░███
#  ░███    ░███ ████  ████████    ███████   █████
#  ░██████████ ░░███ ░░███░░███  ███░░███  ███░░
#  ░███░░░░░███ ░███  ░███ ░███ ░███ ░███ ░░█████
#  ░███    ░███ ░███  ░███ ░███ ░███ ░███  ░░░░███
#  ███████████  █████ ████ █████░░████████ ██████
# ░░░░░░░░░░░  ░░░░░ ░░░░ ░░░░░  ░░░░░░░░ ░░░░░░
# riverctl keyboard-layout -options "caps:escape" us # Map capslock to escape

# Binds

# My Mappings
riverctl map normal $mod Return spawn "$terminal"
riverctl map normal $mod T spawn "$filemanager"
riverctl map normal $mod W spawn "$browser"
# riverctl map normal $mod R spawn "rofi -show drun"
# riverctl map normal $mod O spawn "obsidian"
# riverctl map normal $mod W spawn "ferdium"
# riverctl map normal $mod D spawn "webcord"
# riverctl map normal $mod D spawn "vesktop"
# riverctl map normal $mod G spawn "retroarch"
# riverctl map normal $mod S spawn "spotify-launcher"
# riverctl map normal $mod Y spawn "youtube-music"
# riverctl map normal $mod A spawn "anki"
# riverctl map normal $mod I spawn "ticktick"
# riverctl map normal $mod E spawn "$terminal -e zsh -ic yazi"
# riverctl map normal $mod M spawn "$terminal -e btop"
# riverctl map normal $mod KP_Add spawn "galculator"

riverctl map normal $mod Q close
riverctl map normal $mod+Shift Q exit
riverctl map normal $mod+Control F toggle-float
riverctl map normal $mod F toggle-fullscreen

riverctl map normal $mod S spawn "swaync-client -t -sw"
riverctl map normal $mod+Alt R spawn "$HOME/.config/river/scripts/Refresh.sh >/dev/null && notify-send 'Refreshed River'"

#Scripts
riverctl map normal $mod C spawn "$HOME/scripts/colorpicker"
riverctl map normal $mod Tab spawn "$HOME/scripts/wallchange.sh"
riverctl map normal $mod Grave spawn "$HOME/scripts/list-river-window"
riverctl map normal $mod Escape spawn "$HOME/scripts/rofi-power"
# riverctl map normal $mod+Control W spawn "$HOME/scripts/rofi-wifi"
# riverctl map normal $mod+Control B spawn "$HOME/scripts/rofi-bluetooth"
# riverctl map normal $mod+Control S spawn "$HOME/scripts/rofi-wall"
# riverctl map normal $mod+Control C spawn "$HOME/scripts/text-picker"

# Rofi
riverctl map normal $mod+Control R spawn "$scriptsDir/RofiThemeSelector.sh" # KooL Rofi Menu Theme Selector
riverctl map normal $mod R spawn "pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window"
riverctl map normal $mod+Control SHIFT R spawn "pkill rofi || true && $scriptsDir/RofiThemeSelector-modified.sh"
riverctl map normal $mod+ALT E spawn "$UserScripts/RofiEmoji.sh" # emoji menu
# bind = $mainMod, R, exec, pkill -x rofi || $scriptsDir/rofilaunch.sh d # launch application launcher
# bind = $mainMod Tab spawn "pkill -x rofi || $scrPath/rofilaunch.sh w" # launch window switcher
# bind = $mainMod+Shift, E, exec, pkill -x rofi || $scrPath/rofilaunch.sh f # launch file explorer

# Waybar / Bar related
riverctl map normal $mod+CTRL ALT B spawn "pkill -SIGUSR1 waybar"      # Toggle hide/show waybar
riverctl map normal $mod+Control B spawn "$scriptsDir/WaybarStyles.sh" # Waybar Styles Menu
riverctl map normal $mod+Alt B spawn "$scriptsDir/WaybarLayout.sh"     # Waybar Layout Menu
# FEATURES / EXTRAS (UserScripts)
riverctl map normal $mod+Control M spawn "$UserScripts/RofiBeats.sh"      # online music using rofi
riverctl map normal $mod G spawn "$UserScripts/WallpaperSelect.sh"        # Select wallpaper to apply
riverctl map normal $mod+Shift W spawn "$UserScripts/WallpaperEffects.sh" # Wallpaper Effects by imagemagick
# riverctl map normal $mod W spawn $UserScripts/WallpaperRandom.sh           # Random wallpapers
riverctl map normal $mod+ALT C spawn "$UserScripts/RofiCalc.sh" # calculator (qalculate)

# Screenshots
riverctl map normal None Print spawn "$HOME/scripts/screenshots/captureAll.sh"
riverctl map normal Control Print spawn "$HOME/scripts/screenshots/captureScreen.sh"
riverctl map normal Control+Shift Print spawn "$HOME/scripts/screenshots/captureArea.sh"

riverctl map normal $mod V spawn "cliphist list | rofi -dmenu -p 'Clipboard' -config $HOME/.config/rofi/regular.rasi | cliphist decode | wl-copy"

for i in $(seq 1 9); do
  # Tags are basically workspaces, but different
  tags=$((1 << ("$i" - 1)))
  riverctl map normal $mod "$i" set-focused-tags $(($sticky_tag + $tags))
  riverctl map normal $mod+Shift "$i" set-view-tags $tags
  riverctl map normal $mod+Control "$i" toggle-focused-tags $tags
  riverctl map normal $mod+Shift+Control "$i" toggle-view-tags $tags
done

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Eject the optical drive (well if you still have one that is)
  riverctl map $mode None XF86Eject spawn 'eject -T'

  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  riverctl map $mode None XF86AudioRaiseVolume spawn "$HOME/scripts/volume up"
  riverctl map $mode None XF86AudioLowerVolume spawn "$HOME/scripts/volume down"
  riverctl map $mode None XF86AudioMute spawn "$HOME/scripts/volume mute"

  riverctl map $mode None XF86MonBrightnessUp spawn "$HOME/scripts/brightness up"
  riverctl map $mode None XF86MonBrightnessDown spawn "$HOME/scripts/brightness down"
done

# Mouse binds
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

# $mod+0 to focus all tags
# $mod+Shift+0 to tag focused view with all tags
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

riverctl map-switch normal lid close "swaylock -f"

# $mod+Return to bump the focused view to the top of the layout stack

# Focus windows with $mod h/j/k/l
riverctl map normal $mod+Control H focus-view left
riverctl map normal $mod+Control J focus-view down
riverctl map normal $mod+Control K focus-view up
riverctl map normal $mod+Control L focus-view right

#Focus windows with $mod Arrow keys
riverctl map normal $mod Left focus-view left
riverctl map normal $mod Down focus-view down
riverctl map normal $mod Up focus-view up
riverctl map normal $mod Right focus-view right

# Swap views(windows) with Alt left/right/up/down
riverctl map normal Mod1+Control Left swap left
riverctl map normal Mod1+Control Down swap down
riverctl map normal Mod1+Control Up swap up
riverctl map normal Mod1+Control Right swap right

# $mod+Period and Super+Comma to focus the next/previous output(Monitor/Screen)
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# $mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# FLOATING MAPS
# Move all these binds to a floating mode, since that's where the work
riverctl declare-mode floating
riverctl map normal Alt F enter-mode floating

# -repeat makes the bind repeatable, while it not released
# {H,J,K,L} to resize views by 25
riverctl map -repeat floating None H resize horizontal -25
riverctl map -repeat floating None J resize vertical 25
riverctl map -repeat floating None K resize vertical -25
riverctl map -repeat floating None L resize horizontal 25

# Control+{H,J,K,L} to move views by 25
riverctl map -repeat floating Control H move left 25
riverctl map -repeat floating Control J move down 25
riverctl map -repeat floating Control K move up 25
riverctl map -repeat floating Control L move right 25

# Shift+{H,J,K,L} to snap views to screen edges
riverctl map floating Shift H snap left
riverctl map floating Shift J snap down
riverctl map floating Shift K snap up
riverctl map floating Shift L snap right

riverctl map floating None Escape enter-mode normal

# RESIZE MAPS
# Alt+H and Alt+L to decrease/increase the main ratio of rivertile(1)
riverctl map -repeat normal Mod1 H send-layout-cmd rivertile "main-ratio -0.01"
riverctl map -repeat normal Mod1 L send-layout-cmd rivertile "main-ratio +0.01"

riverctl map normal Mod1+Control K send-layout-cmd rivertile "main-location top"
riverctl map normal Mod1+Control L send-layout-cmd rivertile "main-location right"
riverctl map normal Mod1+Control J send-layout-cmd rivertile "main-location bottom"
riverctl map normal Mod1+Control H send-layout-cmd rivertile "main-location left"

# Shift+H and Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Mod1+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Mod1+Shift L send-layout-cmd rivertile "main-count -1"

# PASSTHROUGH MAP
# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough
# $mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough
# $mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

#  ███████████              ████
# ░░███░░░░░███            ░░███
#  ░███    ░███  █████ ████ ░███   ██████   █████
#  ░██████████  ░░███ ░███  ░███  ███░░███ ███░░
#  ░███░░░░░███  ░███ ░███  ░███ ░███████ ░░█████
#  ░███    ░███  ░███ ░███  ░███ ░███░░░   ░░░░███
#  █████   █████ ░░████████ █████░░██████  ██████
# ░░░░░   ░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░  ░░░░░░

# Rules
# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add ssd

riverctl rule-add -app-id "floorp" tags $browser_tag
riverctl rule-add -app-id "zen" tags $browser_tag
riverctl rule-add -app-id "firefox" tags $browser_tag
riverctl rule-add -app-id "Code" tags $code_tag
riverctl rule-add -app-id "anki" tags $code_tag
riverctl rule-add -app-id "special-go" tags $code_tag
riverctl rule-add -app-id "dev.zed.Zed" tags $code_tag
riverctl rule-add -app-id "org.gnome.Nautilus" tags $file_browser_tag
riverctl rule-add -app-id "thunar" tags $file_browser_tag
riverctl rule-add -app-id "org.kde.dolphin" tags $file_browser_tag
riverctl rule-add -app-id "com.libretro.RetroArch" tags $games_tag
riverctl rule-add -app-id "Celeste.bin.x86_64" tags $games_tag
riverctl rule-add -app-id "hollow_knight.x86_64" tags $games_tag
riverctl rule-add -title "Brawlhalla" tags $games_tag
riverctl rule-add -app-id "citra-qt" tags $games_tag
riverctl rule-add -app-id "es-de" tags $games_tag
riverctl rule-add -app-id "steam" tags $games_tag
riverctl rule-add -app-id "Ferdium" tags $socials_tag
riverctl rule-add -app-id "org.telegram.desktop" tags $socials_tag
riverctl rule-add -app-id "WebCord" tags $discord_tag
riverctl rule-add -app-id "vesktop" tags $discord_tag
riverctl rule-add -app-id "obsidian" tags $obsidian_tag

riverctl rule-add -app-id "special-term" tags $terminal_tag
riverctl rule-add -app-id "special-files" tags $files_tag
riverctl rule-add -app-id "special-nvim" tags $dots_tag
riverctl rule-add -app-id "special-btop" tags $monitor_tag
riverctl rule-add -app-id "special-project" tags $project_tag
riverctl rule-add -app-id "ticktick" tags $ticktick_tag
riverctl rule-add -app-id "mpv" tags $docs_tag
riverctl rule-add -app-id "org.pwmt.zathura" tags $docs_tag
riverctl rule-add -app-id "Spotify" tags $spotify_tag
riverctl rule-add -title "YouTube Music" tags $spotify_tag
riverctl rule-add -app-id "org.qbittorrent.qBittorrent" tags $special_tag

riverctl rule-add -app-id "anki" csd

riverctl rule-add -title "Brawlhalla" fullscreen
riverctl rule-add -app-id "org.pwmt.zathura" fullscreen
riverctl rule-add -app-id "mpv" fullscreen
riverctl rule-add -app-id "Spotify" fullscreen
riverctl rule-add -app-id "ticktick" fullscreen
riverctl rule-add -app-id "feh" fullscreen
riverctl rule-add -app-id "com.libretro.RetroArch" fullscreen
riverctl rule-add -app-id "es-de" fullscreen

riverctl rule-add -title "Special Offers" float # Steam
riverctl rule-add -title "Friends List" float   # Steam
riverctl rule-add -title "Steam Settings" float # Steam
riverctl rule-add -app-id "steam" -title "Brawlhalla" float
riverctl rule-add -app-id "galculator" float
riverctl rule-add -app-id "org.kde.kcalc" float
riverctl rule-add -app-id "blueman-manager" float
riverctl rule-add -app-id "org.kde.kdeconnect.app" float
riverctl rule-add -app-id "nm-connection-editor" float
riverctl rule-add -app-id "org.kde.polkit-kde-authentication-agent-1" float
riverctl rule-add -app-id "polkit-gnome-authentication-agent-1" float
riverctl rule-add -app-id "org.qbittorrent.qBittorrent" float

riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float
riverctl rule-add -app-id 'GParted' float
riverctl rule-add -app-id 'nwg-look' float
riverctl rule-add -app-id 'firefox' -title 'Picture-in-Picture' float
riverctl rule-add -app-id 'floorp' -title 'Picture-in-Picture' float
riverctl rule-add -app-id 'zen' -title 'Picture-in-Picture' float
riverctl rule-add -title 'gtk*' float
riverctl rule-add -app-id 'xdg-desktop-portal-gtk' float

riverctl rule-add -app-id float float
riverctl rule-add -title "popup title with spaces" float
riverctl rule-add -title "zoom" float
riverctl rule-add -title "Picture-in-Picture" float

$HOME/.config/river/proces.sh
