#! /bin/sh

export EDITOR=nivm 

wmname LG3D & # fix for some Java apps

# Set configurations
for i in "$HOME"/.config/bspwm/configs/*.sh; do
	{
		eval "$i" &
	}
done

# Autostart
eval "$HOME/.config/bspwm/autostart.sh" &

# Set rules
for i in "$HOME"/.config/bspwm/rules/*.sh; do
	{
		eval "$i" &
	}
done

# Start playerctld daemon to monitor playback
playerctld daemon &

# Delete existing hooks and restart them
for i in "$HOME"/.config/bspwm/hooks/*.sh; do
	{
		pkill -9 -f "$i"
		eval "$i" &
	}
done

if xrandr -q | grep 'HDMI-1 connected'; then
    xrandr  --output eDP-1 --mode 1366x768 --output HDMI-1 --mode 1366x768 --right-of eDP-1
    bspc monitor eDP-1 -d 一 二 三 四 五
    bspc monitor HDMI-1 -d 五 六 七 八
else
   # bspc monitor LVDS-1  -d I II III IV V VI VII VIII IX X
    bspc monitor eDP-1  -d    二 三 四 五 六
   
fi
xrandr --output eDP-1 --mode 1366x768
#

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar close-all
  else
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar open bar
    fi
done &

# pkill eww &

# $HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# eww -c ~/.config/eww/barol/ open bar


# $HOME/.config/polybar/launch.sh
