#! /bin/sh

# export SUDO_ASKPASS="$HOME/.local/bin/scripts/pass "
# export PATH="${PATH}:$HOME/.local/bin/scripts"
# export PATH="$PATH:$(du "$HOME/.local/bin/modulos/" | cut -f2 | paste -sd ':' -)"
export EDITOR=nivm 
sxhkd &
picom --experimental-backends &
nitrogen --restore &
startup &
pgrep -x sxhkd > /dev/null
temas &
wmname LG3D & # fix for some Java apps
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &          
eval $(gnome-keyring-daemon -s -- components=pkcs11,secrets,ssh,gpg) 
xsetroot -cursor_name left_ptr &

# Launching polybar
bash "$HOME/.config/polybar/launch.sh" &

# fix pointer
xsetroot -cursor_name left_ptr &

# Set configurations
for i in "$HOME"/.config/bspwm/configs/*.sh; do
	{
		eval "$i" &
	}
done

# Autostart
eval "$HOME/.config/bspwm/autostart.sh" &

# Set rules
for i in "$HOME"/.config/bspwm/rules/*.sh; do
	{
		eval "$i" &
	}
done


# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Start copyq
copyq --start-server &

# Start playerctld daemon to monitor playback
playerctld daemon &

# Start compositor
while pgrep -u "$UID" -x picom >/dev/null; do sleep 1; done
picom &

# Delete existing hooks and restart them
for i in "$HOME"/.config/bspwm/hooks/*.sh; do
	{
		pkill -9 -f "$i"
		eval "$i" &
	}
done

# Reached end of script
pkill -9 -f "dunst"
dunstify -i window_list "Successfully restarted BSPWM"


# bspc monitor -d I II III IV V VI VII VIII IX X
# if xrandr -q | grep 'HDMI1 connected'; then
#     xrandr  --output LVDS1 --mode 1366x768 --output HDMI1 --mode 1366x768 --right-of LVDS1  
#     bspc monitor LVDS1 -d 一 二 三 四 
#     bspc monitor HDMI1 -d 五 六 七 八 九 十
# else
#    # bspc monitor LVDS-1  -d I II III IV V VI VII VIII IX X
#     bspc monitor eDP1  -d    二 三 四 五 六 七 八 九 十
#    
# fi
xrandr --output eDP1 --mode 1366x768
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

 bspc config border_width    2
bspc config window_gap      4
bspc config top_padding     20
bspc config bottom_padding  0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config automatic_scheme longest_side
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config focused_frame_opacity 0.05
#bspc config normal_frame_opacity 1.0                                
#___________________ FullCOLOR Theme _______________________
bspc config urgent_border_color "#dd2727"
bspc config focused_border_color "#03B4CB"
bspc config presel_feedback_color "#FF492B"


# $HOME/.config/polybar/launch.sh
