#! /bin/sh

# export SUDO_ASKPASS="$HOME/.local/bin/scripts/pass "
# export PATH="${PATH}:$HOME/.local/bin/scripts"
# export PATH="$PATH:$(du "$HOME/.local/bin/modulos/" | cut -f2 | paste -sd ':' -)"
export EDITOR=nivm 

# picom --experimental-backends &
# sxhkd &
# pgrep -x sxhkd > /dev/null
# temas &
wmname LG3D & # fix for some Java apps
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &          
# eval $(gnome-keyring-daemon -s -- components=pkcs11,secrets,ssh,gpg) 

# Set configurations
for i in "$HOME"/.config/bspwm/configs/*.sh; do
	{
		eval "$i" &
	}
done

# Autostart
eval "$HOME/.config/bspwm/autostart.sh" &

# Set rules
for i in "$HOME"/.config/bspwm/rules/*.sh; do
	{
		eval "$i" &
	}
done


# Enable Super Keys For Menu
# ksuperkey -e 'Super_L=Alt_L|F1' &
# ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
# if [[ ! $(pidof xfce-polkit) ]]; then
# 	/usr/lib/xfce-polkit/xfce-polkit &
# fi

# Start playerctld daemon to monitor playback
playerctld daemon &

# Delete existing hooks and restart them
for i in "$HOME"/.config/bspwm/hooks/*.sh; do
	{
		pkill -9 -f "$i"
		eval "$i" &
	}
done

# if xrandr -q | grep 'HDMI-1 connected'; then
#     xrandr  --output eDP-1 --mode 1366x768 --output HDMI-1 --mode 1366x768 --right-of eDP-1
#     bspc monitor eDP-1 -d 一 二 三 四 五
#     bspc monitor HDMI-1 -d 五 六 七 八
# else
#    # bspc monitor LVDS-1  -d I II III IV V VI VII VIII IX X
#     bspc monitor eDP-1  -d    二 三 四 五 六
   
# fi
# xrandr --output eDP-1 --mode 1366x768
#

workspaces() {
  name=1
  for monitor in $(bspc query -M); do
    # bspc monitor "${monitor}" -n "$name" -d '' '' '' '' '' '' ''
    bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6' '7'
    ((name++))
  done
}
workspaces

# bspc subscribe node_state | while read -r _ _ _ _ state flag; do
#     if [ "$state" != "fullscreen" ]; then
#         continue
#     fi
#     if [ "$flag" == on ]; then
#         $HOME/.local/bin/eww -c $HOME/.config/eww/bar close-all
#   else
#         $HOME/.local/bin/eww -c $HOME/.config/eww/bar open bar
#     fi
# done &
pkill eww
eww open bar

# $HOME/.config/polybar/launch.sh

# $HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &
