require "user.plugins"
require "user.autopairs"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.barbar"
require "user.gitsigns"
-- require "user.illuminate"
require "user.impatient"
require "user.indentline"
require "user.keymaps"
require "user.lualine"
require "user.lsp"
require "user.nvim-tree"
require "user.options"
require "user.colorized"
require "user.whichkey"
require "user.project"
require "user.treesitter"
require "user.telescope"
require "user.dap"
require "user.rest"
require "user.lspsaga"
require "user.notify"
-- require "user.bfs"

vim.cmd('runtime ./lua/user/floatterm.vim')
vim.cmd('runtime ./lua/user/tagalone.vim')
